/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Public Config
         * @description Configuración PÚBLICA para la web (sin sesión): la llave publicable de Clerk (es pública por diseño).
         */
        get: operations["public_config_config_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Me */
        get: operations["me_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/link-legacy": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Link Legacy
         * @description Vincula el perfil que la persona usaba en la versión anterior (Streamlit), con su contraseña.
         */
        post: operations["link_legacy_me_link_legacy_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/contact": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Update Contact */
        put: operations["update_contact_me_contact_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Profile */
        get: operations["get_profile_profile_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/experiences": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Add Experience */
        post: operations["add_experience_experiences_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/experiences/{experience_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Update Experience */
        put: operations["update_experience_experiences__experience_id__put"];
        post?: never;
        /** Delete Experience */
        delete: operations["delete_experience_experiences__experience_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/experiences/{experience_id}/achievements": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Append Achievements */
        post: operations["append_achievements_experiences__experience_id__achievements_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/skills": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Add Skill */
        post: operations["add_skill_skills_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/skills/{skill_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Skill */
        delete: operations["delete_skill_skills__skill_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/education": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Add Education */
        post: operations["add_education_education_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/education/{education_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Education */
        delete: operations["delete_education_education__education_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/profile/import": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Import Cv
         * @description Lee el PDF en segundo plano. El resultado del trabajo trae lo leído, lo descartado y lo repetido.
         *
         *     Función normal (no async): leer el PDF es trabajo síncrono y así corre en el pool de hilos sin
         *     detener las demás peticiones.
         */
        post: operations["import_cv_profile_import_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/profile/import/{job_id}/apply": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Apply Import */
        post: operations["apply_import_profile_import__job_id__apply_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/experiences/{experience_id}/suggestions/from-text": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * From Text
         * @description «Cuéntame todo lo que hacías»: texto libre → logros separados y verificados.
         */
        post: operations["from_text_experiences__experience_id__suggestions_from_text_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/experiences/{experience_id}/suggestions/tasks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Typical Tasks
         * @description Tareas típicas del cargo para marcar las que sí hiciste.
         */
        post: operations["typical_tasks_experiences__experience_id__suggestions_tasks_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/experiences/{experience_id}/suggestions/from-tasks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** From Tasks */
        post: operations["from_tasks_experiences__experience_id__suggestions_from_tasks_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/experiences/{experience_id}/interview/questions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Interview Questions */
        post: operations["interview_questions_experiences__experience_id__interview_questions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/experiences/{experience_id}/interview/proposals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Interview Proposals */
        post: operations["interview_proposals_experiences__experience_id__interview_proposals_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/experiences/{experience_id}/interview/accept": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Interview Accept
         * @description Aplica las mejoras elegidas: reemplaza cada logro mejorado en su lugar y agrega los nuevos.
         */
        post: operations["interview_accept_experiences__experience_id__interview_accept_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/applications": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Applications */
        get: operations["list_applications_applications_get"];
        put?: never;
        /** Create Application */
        post: operations["create_application_applications_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/applications/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Summary */
        get: operations["summary_applications_summary_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/applications/{application_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Application */
        get: operations["get_application_applications__application_id__get"];
        put?: never;
        post?: never;
        /** Delete Application */
        delete: operations["delete_application_applications__application_id__delete"];
        options?: never;
        head?: never;
        /** Update Details */
        patch: operations["update_details_applications__application_id__patch"];
        trace?: never;
    };
    "/applications/{application_id}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Change Status */
        post: operations["change_status_applications__application_id__status_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/applications/{application_id}/notes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Add Note */
        post: operations["add_note_applications__application_id__notes_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/applications/{application_id}/follow-up": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Set Follow Up */
        put: operations["set_follow_up_applications__application_id__follow_up_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/applications/{application_id}/sent": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Mark Sent */
        post: operations["mark_sent_applications__application_id__sent_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cvs/{cv_id}/{fmt}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Download Cv
         * @description El archivo exacto que se guardó; si no coincide con su huella, no se entrega.
         */
        get: operations["download_cv_cvs__cv_id___fmt__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/market": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Market */
        get: operations["market_market_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/vacancies": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Add Vacancy
         * @description Trae (enlace) o recibe (texto) una vacante, la analiza y la guarda. 409 si ya la tienes.
         */
        post: operations["add_vacancy_vacancies_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/applications/{application_id}/analysis": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Analysis
         * @description Compatibilidad con el perfil actual, sin IA (recalculada con las evidencias guardadas).
         */
        get: operations["get_analysis_applications__application_id__analysis_get"];
        put?: never;
        /**
         * Refresh Analysis
         * @description Vuelve a buscar evidencias con la IA (tras cambiar el perfil).
         */
        post: operations["refresh_analysis_applications__application_id__analysis_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/applications/{application_id}/prepare": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Prepare
         * @description «Preparar postulación» desde la bandeja.
         */
        post: operations["prepare_applications__application_id__prepare_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/inbox": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Add To Inbox */
        post: operations["add_to_inbox_inbox_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/discovery/titles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Suggest Titles */
        get: operations["suggest_titles_discovery_titles_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/discovery/links": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Search Links */
        get: operations["search_links_discovery_links_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/applications/{application_id}/cvs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Generate Cv
         * @description Genera el CV en segundo plano; el resultado (`cv_id`) aparece en el trabajo.
         */
        post: operations["generate_cv_applications__application_id__cvs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cvs/{cv_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Cv */
        get: operations["get_cv_cvs__cv_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cvs/{cv_id}/document": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Edit Cv
         * @description Guarda una versión nueva del CV con las ediciones; el original no se toca. Cuenta en el cupo diario
         *     como una llamada (no usa IA, pero genera y guarda un PDF nuevo).
         */
        put: operations["edit_cv_cvs__cv_id__document_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/applications/{application_id}/screening": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Screening */
        post: operations["screening_applications__application_id__screening_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/applications/{application_id}/cover": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Cover */
        post: operations["cover_applications__application_id__cover_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/applications/{application_id}/gaps": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Gap
         * @description «Sí lo he hecho»: lo contado sobre un requisito faltante se agrega como logros verificados.
         */
        post: operations["gap_applications__application_id__gaps_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Job */
        get: operations["get_job_jobs__job_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/usage": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Usage */
        get: operations["get_usage_usage_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/dev/token": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Dev Token */
        post: operations["dev_token_dev_token_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AcceptIn */
        AcceptIn: {
            /** Accepted */
            accepted: components["schemas"]["AcceptedIn"][];
            /**
             * Answers
             * @description Las respuestas de la entrevista: el servidor verifica contra ellas
             */
            answers: string[];
        };
        /** AcceptedIn */
        AcceptedIn: {
            /** Achievement Id */
            achievement_id?: number | null;
            /** Text */
            text: string;
        };
        /** AchievementOut */
        AchievementOut: {
            /** Id */
            id: number;
            /** Text */
            text: string;
        };
        /** AchievementsIn */
        AchievementsIn: {
            /** Texts */
            texts: string[];
        };
        /** AnalysisOut */
        AnalysisOut: {
            /** Application Id */
            application_id: number;
            /** Status */
            status: string;
            /** Vacancy */
            vacancy: {
                [key: string]: unknown;
            };
            /** @description null: nunca se calculó (POST /applications/{id}/analysis) */
            match: components["schemas"]["MatchOut"] | null;
            /**
             * Stale
             * @description Tu perfil cambió desde el análisis: actualízalo antes de generar
             */
            stale: boolean;
        };
        /** AnswerIn */
        AnswerIn: {
            /** Achievement Id */
            achievement_id?: number | null;
            /** Question */
            question: string;
            /**
             * Answer
             * @default
             */
            answer: string;
        };
        /** AnswersIn */
        AnswersIn: {
            /** Answers */
            answers: components["schemas"]["AnswerIn"][];
        };
        /**
         * ApplicationIn
         * @description Postulación hecha por fuera de la app.
         */
        ApplicationIn: {
            /** Role */
            role: string;
            /**
             * Company
             * @default
             */
            company: string;
            /**
             * Platform
             * @default
             * @enum {string}
             */
            platform: "" | "LinkedIn" | "Computrabajo" | "Magneto" | "elempleo" | "Página de la empresa" | "Correo o referido" | "Otra";
            /**
             * Url
             * @default
             */
            url: string;
            /**
             * Status
             * @default postulada
             * @enum {string}
             */
            status: "guardada" | "cv_generado" | "postulada" | "en_revision" | "entrevista" | "oferta" | "rechazada" | "retirada" | "descartada";
            /** Applied On */
            applied_on?: string | null;
        };
        /** ApplicationOut */
        ApplicationOut: {
            /** Id */
            id: number;
            /** Role */
            role: string;
            /** Company */
            company: string;
            /** Platform */
            platform: string;
            /** Url */
            url: string;
            /** Status */
            status: string;
            /** Status Label */
            status_label: string;
            /** Match Score */
            match_score: number | null;
            /** Applied On */
            applied_on: string | null;
            /** Next Action On */
            next_action_on: string | null;
            /** Next Action */
            next_action: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /**
             * Missing Musts
             * @description Requisitos obligatorios que no cumples
             */
            missing_musts?: string[];
            /**
             * Partial Musts
             * @description Obligatorios que cumples a medias
             */
            partial_musts?: string[];
            /** Contact */
            contact: string;
            /** Vacancy Text */
            vacancy_text: string;
            /**
             * Vacancy
             * @description Análisis estructurado de la vacante
             */
            vacancy: {
                [key: string]: unknown;
            } | null;
            /**
             * Match
             * @description Resumen de compatibilidad guardado
             */
            match: {
                [key: string]: unknown;
            } | null;
            /** Events */
            events: components["schemas"]["EventOut"][];
            /** Cvs */
            cvs: components["schemas"]["CVOut"][];
        };
        /** ApplicationSummaryOut */
        ApplicationSummaryOut: {
            /** Id */
            id: number;
            /** Role */
            role: string;
            /** Company */
            company: string;
            /** Platform */
            platform: string;
            /** Url */
            url: string;
            /** Status */
            status: string;
            /** Status Label */
            status_label: string;
            /** Match Score */
            match_score: number | null;
            /** Applied On */
            applied_on: string | null;
            /** Next Action On */
            next_action_on: string | null;
            /** Next Action */
            next_action: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /**
             * Missing Musts
             * @description Requisitos obligatorios que no cumples
             */
            missing_musts?: string[];
            /**
             * Partial Musts
             * @description Obligatorios que cumples a medias
             */
            partial_musts?: string[];
        };
        /** Body_import_cv_profile_import_post */
        Body_import_cv_profile_import_post: {
            /**
             * File
             * @description CV o PDF de LinkedIn
             */
            file: string;
        };
        /** CVBulletEdit */
        CVBulletEdit: {
            /** Text */
            text: string;
            /**
             * Included
             * @default true
             */
            included: boolean;
        };
        /** CVDetailOut */
        CVDetailOut: {
            /** Id */
            id: number;
            /** Language */
            language: string;
            /** Filename */
            filename: string;
            /** Pdf Sha256 */
            pdf_sha256: string;
            /** Sent At */
            sent_at: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Intact
             * @description El PDF y el DOCX coinciden con su huella
             */
            intact: boolean;
            /** Application Id */
            application_id: number;
            /** Markdown */
            markdown: string;
            /**
             * Document
             * @description Documento estructurado (null: CV anterior a la edición)
             */
            document: {
                [key: string]: unknown;
            } | null;
        };
        /** CVEditIn */
        CVEditIn: {
            /** Summary */
            summary: string;
            /** Experiences */
            experiences: components["schemas"]["CVExperienceEdit"][];
        };
        /** CVExperienceEdit */
        CVExperienceEdit: {
            /** Bullets */
            bullets: components["schemas"]["CVBulletEdit"][];
        };
        /** CVOut */
        CVOut: {
            /** Id */
            id: number;
            /** Language */
            language: string;
            /** Filename */
            filename: string;
            /** Pdf Sha256 */
            pdf_sha256: string;
            /** Sent At */
            sent_at: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Intact
             * @description El PDF y el DOCX coinciden con su huella
             */
            intact: boolean;
        };
        /** CVResultOut */
        CVResultOut: {
            /** Cv Id */
            cv_id: number;
            /** Filename */
            filename: string;
            /** Pages */
            pages: number;
            /**
             * Trimmed
             * @description Lo que se quitó para caber en 1 página
             */
            trimmed: string[];
        };
        /** CandidateOut */
        CandidateOut: {
            /** Text */
            text: string;
            /** Problems */
            problems: string[];
            /** Duplicate Of */
            duplicate_of: string | null;
            /**
             * Suggested
             * @description Verificado y no repetido (en /gaps: ya se agregó al perfil)
             */
            suggested: boolean;
        };
        /**
         * Contact
         * @description Entrada: valida los enlaces (acepta "www.linkedin.com/in/..." y le agrega https://).
         */
        Contact: {
            /**
             * Full Name
             * @default
             */
            full_name: string;
            /**
             * Email
             * @default
             */
            email: string;
            /**
             * Phone
             * @default
             */
            phone: string;
            /**
             * Linkedin Url
             * @default
             */
            linkedin_url: string;
            /**
             * Github Url
             * @default
             */
            github_url: string;
        };
        /**
         * ContactOut
         * @description Salida: tal como está guardado (perfiles de Streamlit o importados pueden tener otros formatos).
         */
        ContactOut: {
            /** Full Name */
            full_name: string;
            /** Email */
            email: string;
            /** Phone */
            phone: string;
            /** Linkedin Url */
            linkedin_url: string;
            /** Github Url */
            github_url: string;
        };
        /** CoverOut */
        CoverOut: {
            /** Text */
            text: string;
            /**
             * Fallback
             * @description La IA inventó algo y se usó un mensaje con solo datos reales
             */
            fallback: boolean;
            /** Problems */
            problems: string[];
        };
        /** DetailsIn */
        DetailsIn: {
            /** Role */
            role?: string | null;
            /** Company */
            company?: string | null;
            /** Platform */
            platform?: ("" | "LinkedIn" | "Computrabajo" | "Magneto" | "elempleo" | "Página de la empresa" | "Correo o referido" | "Otra") | null;
            /** Url */
            url?: string | null;
            /** Contact */
            contact?: string | null;
        };
        /** DevLoginIn */
        DevLoginIn: {
            /** Name */
            name: string;
        };
        /** DevTokenOut */
        DevTokenOut: {
            /** Token */
            token: string;
            /** Expires In */
            expires_in: number;
        };
        /** EducationIn */
        EducationIn: {
            /** Title */
            title: string;
            /**
             * Institution
             * @default
             */
            institution: string;
            /**
             * Period Text
             * @default
             */
            period_text: string;
            /**
             * Description
             * @default
             */
            description: string;
        };
        /** EducationOut */
        EducationOut: {
            /** Id */
            id: number;
            /** Title */
            title: string;
            /** Institution */
            institution: string;
            /** Period Text */
            period_text: string;
            /** Description */
            description: string;
        };
        /** EventOut */
        EventOut: {
            /** Id */
            id: number;
            /** Kind */
            kind: string;
            /** From Status */
            from_status: string;
            /** To Status */
            to_status: string;
            /** Detail */
            detail: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** EvidenceOut */
        EvidenceOut: {
            /** Ref */
            ref: string;
            /** Label */
            label: string;
        };
        /** ExperienceIn */
        ExperienceIn: {
            /** Role */
            role: string;
            /**
             * Company
             * @default
             */
            company: string;
            /**
             * Period Text
             * @default
             */
            period_text: string;
            /**
             * Country
             * @default
             */
            country: string;
            /**
             * Modality
             * @default
             */
            modality: string;
            /** Achievements */
            achievements?: string[];
        };
        /** ExperienceOut */
        ExperienceOut: {
            /** Id */
            id: number;
            /** Role */
            role: string;
            /** Company */
            company: string;
            /** Period Text */
            period_text: string;
            /** Country */
            country: string;
            /** Modality */
            modality: string;
            /** Achievements */
            achievements: components["schemas"]["AchievementOut"][];
        };
        /** FollowUpIn */
        FollowUpIn: {
            /**
             * On
             * @description Fecha del recordatorio; null lo quita
             */
            on: string | null;
            /**
             * What
             * @default
             */
            what: string;
        };
        /** FreeTextIn */
        FreeTextIn: {
            /** Text */
            text: string;
        };
        /** GapIn */
        GapIn: {
            /**
             * Requirement
             * @description Índice del requisito (0 = el primero)
             */
            requirement: number;
            /** Experience Id */
            experience_id: number;
            /** Story */
            story: string;
        };
        /** GapOut */
        GapOut: {
            /** Added */
            added: number;
            /** Candidates */
            candidates: components["schemas"]["CandidateOut"][];
        };
        /** GenerateCVIn */
        GenerateCVIn: {
            /**
             * Focus
             * @default
             */
            focus: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** ImportApplyIn */
        ImportApplyIn: {
            /**
             * Experiences
             * @description Índices de la lectura
             */
            experiences?: number[];
            /** Skills */
            skills?: number[];
            /** Education */
            education?: number[];
            /**
             * Fill Contact
             * @description Completar nombre, correo, teléfono y LinkedIn vacíos
             * @default true
             */
            fill_contact: boolean;
        };
        /** ImportApplyOut */
        ImportApplyOut: {
            /** Counts */
            counts: {
                [key: string]: number;
            };
            profile: components["schemas"]["ProfileOut"];
        };
        /** InboxIn */
        InboxIn: {
            /**
             * Links
             * @description Enlaces, uno por línea o mezclados
             */
            links: string;
        };
        /** InboxOut */
        InboxOut: {
            job: components["schemas"]["JobOut"];
            /** Accepted */
            accepted: string[];
            /**
             * Skipped
             * @description Enlaces de más (se procesan 10 por carga)
             */
            skipped: number;
        };
        /** JobOut */
        JobOut: {
            /** Id */
            id: number;
            /** Kind */
            kind: string;
            /**
             * Status
             * @description queued | running | done | failed
             */
            status: string;
            /** Result */
            result: {
                [key: string]: unknown;
            } | null;
            /** Error */
            error: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Finished At */
            finished_at: string | null;
        };
        /** KeywordOut */
        KeywordOut: {
            /** Keyword */
            keyword: string;
            /** Vacancies */
            vacancies: number;
            /** Share */
            share: number;
            /** Owned */
            owned: boolean;
        };
        /** LinkLegacyIn */
        LinkLegacyIn: {
            /** Username */
            username: string;
            /** Password */
            password: string;
        };
        /** MarketOut */
        MarketOut: {
            /** Applications */
            applications: number;
            /** Analyzed */
            analyzed: number;
            /** Sent */
            sent: number;
            /** Enough Data */
            enough_data: boolean;
            /** Platforms */
            platforms: components["schemas"]["PlatformStatsOut"][];
            /** Keywords */
            keywords: components["schemas"]["KeywordOut"][];
            /** Score Buckets */
            score_buckets: components["schemas"]["ScoreBucketOut"][];
        };
        /** MatchOut */
        MatchOut: {
            /** Score */
            score: number;
            /** Experience Years */
            experience_years: number;
            /** Required Years */
            required_years: number | null;
            /** Meets Years */
            meets_years: boolean | null;
            /** Requirements */
            requirements: components["schemas"]["RequirementOut"][];
        };
        /** MeOut */
        MeOut: {
            /** Email */
            email: string;
            contact: components["schemas"]["ContactOut"];
            /** Has Experience */
            has_experience: boolean;
            /** Has Skills */
            has_skills: boolean;
            /** Has Education */
            has_education: boolean;
        };
        /** NoteIn */
        NoteIn: {
            /** Note */
            note: string;
        };
        /** PlatformStatsOut */
        PlatformStatsOut: {
            /** Platform */
            platform: string;
            /** Saved */
            saved: number;
            /** Sent */
            sent: number;
            /** Progressed */
            progressed: number;
            /** Rejected */
            rejected: number;
            /** Progress Rate */
            progress_rate: number | null;
            /** Avg Score */
            avg_score: number | null;
        };
        /** ProfileOut */
        ProfileOut: {
            contact: components["schemas"]["ContactOut"];
            /** Experiences */
            experiences: components["schemas"]["ExperienceOut"][];
            /** Skills */
            skills: components["schemas"]["SkillOut"][];
            /** Education */
            education: components["schemas"]["EducationOut"][];
            /**
             * Achievements With Numbers
             * @description Logros con cifras (los que más pesan en el CV)
             */
            achievements_with_numbers: number;
            /** Achievements Total */
            achievements_total: number;
        };
        /** ProposalOut */
        ProposalOut: {
            /**
             * Achievement Id
             * @description Logro que mejora; null si es uno nuevo
             */
            achievement_id: number | null;
            /** Original */
            original: string;
            /** Proposed */
            proposed: string;
            /**
             * Problems
             * @description Datos que no salen de tus respuestas: no se recomienda aceptarla
             */
            problems: string[];
        };
        /** QuestionOut */
        QuestionOut: {
            /** Achievement Id */
            achievement_id: number | null;
            /** Question */
            question: string;
            /** Example */
            example: string;
        };
        /** RequirementOut */
        RequirementOut: {
            /** Index */
            index: number;
            /** Text */
            text: string;
            /** Kind */
            kind: string;
            /** Category */
            category: string;
            /**
             * Level
             * @description cubre | parcial | no
             */
            level: string;
            /** Note */
            note: string;
            /** Evidence */
            evidence: components["schemas"]["EvidenceOut"][];
        };
        /** ScoreBucketOut */
        ScoreBucketOut: {
            /** Range */
            range: string;
            /** Sent */
            sent: number;
            /** Progressed */
            progressed: number;
        };
        /** ScreeningAnswerOut */
        ScreeningAnswerOut: {
            /** Question */
            question: string;
            /** Answer */
            answer: string;
            /** Needs You */
            needs_you: boolean;
            /** Note */
            note: string;
        };
        /** ScreeningIn */
        ScreeningIn: {
            /** Questions */
            questions: string[];
        };
        /** SearchLinkOut */
        SearchLinkOut: {
            /** Portal */
            portal: string;
            /** Url */
            url: string;
        };
        /** SentIn */
        SentIn: {
            /**
             * Cv Id
             * @description CV enviado: debe ser de esta misma postulación
             */
            cv_id?: number | null;
            /** Sent On */
            sent_on?: string | null;
            /**
             * Platform
             * @default
             * @enum {string}
             */
            platform: "" | "LinkedIn" | "Computrabajo" | "Magneto" | "elempleo" | "Página de la empresa" | "Correo o referido" | "Otra";
        };
        /** SkillIn */
        SkillIn: {
            /** Name */
            name: string;
            /**
             * Category
             * @default Otros
             */
            category: string;
        };
        /** SkillOut */
        SkillOut: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Category */
            category: string;
        };
        /** StatusIn */
        StatusIn: {
            /**
             * Status
             * @enum {string}
             */
            status: "por_revisar" | "guardada" | "cv_generado" | "postulada" | "en_revision" | "entrevista" | "oferta" | "rechazada" | "retirada" | "descartada";
            /**
             * Note
             * @default
             */
            note: string;
        };
        /** SummaryOut */
        SummaryOut: {
            /** Total */
            total: number;
            /** Sent */
            sent: number;
            /** Responses */
            responses: number;
            /** Response Rate */
            response_rate: number | null;
            /** By Status */
            by_status: {
                [key: string]: number;
            };
            /** Due */
            due: components["schemas"]["ApplicationSummaryOut"][];
        };
        /** TaskItem */
        TaskItem: {
            /** Task */
            task: string;
            /**
             * Detail
             * @default
             */
            detail: string;
        };
        /** TasksIn */
        TasksIn: {
            /** Items */
            items: components["schemas"]["TaskItem"][];
        };
        /** TasksOut */
        TasksOut: {
            /** Tasks */
            tasks: string[];
        };
        /** TitlesOut */
        TitlesOut: {
            /** Titles */
            titles: string[];
        };
        /** UsageOut */
        UsageOut: {
            /** Used Today */
            used_today: number;
            /** Daily Limit */
            daily_limit: number;
        };
        /** VacancyIn */
        VacancyIn: {
            /**
             * Text
             * @default
             */
            text: string;
            /**
             * Url
             * @default
             */
            url: string;
            /**
             * Prepare
             * @description true: lista para postular; false: a la bandeja
             * @default false
             */
            prepare: boolean;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    public_config_config_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    me_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeOut"];
                };
            };
        };
    };
    link_legacy_me_link_legacy_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LinkLegacyIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_contact_me_contact_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Contact"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ContactOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_profile_profile_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfileOut"];
                };
            };
        };
    };
    add_experience_experiences_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExperienceIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfileOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_experience_experiences__experience_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                experience_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExperienceIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfileOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_experience_experiences__experience_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                experience_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfileOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    append_achievements_experiences__experience_id__achievements_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                experience_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AchievementsIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfileOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_skill_skills_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SkillIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfileOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_skill_skills__skill_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                skill_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfileOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_education_education_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EducationIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfileOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_education_education__education_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                education_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfileOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    import_cv_profile_import_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_import_cv_profile_import_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    apply_import_profile_import__job_id__apply_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ImportApplyIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImportApplyOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    from_text_experiences__experience_id__suggestions_from_text_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                experience_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FreeTextIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CandidateOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    typical_tasks_experiences__experience_id__suggestions_tasks_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                experience_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TasksOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    from_tasks_experiences__experience_id__suggestions_from_tasks_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                experience_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TasksIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CandidateOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    interview_questions_experiences__experience_id__interview_questions_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                experience_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QuestionOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    interview_proposals_experiences__experience_id__interview_proposals_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                experience_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AnswersIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProposalOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    interview_accept_experiences__experience_id__interview_accept_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                experience_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AcceptIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfileOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_applications_applications_get: {
        parameters: {
            query?: {
                view?: "activas" | "cerradas" | "todas" | "bandeja" | "descartadas";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApplicationSummaryOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_application_applications_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ApplicationIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApplicationOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    summary_applications_summary_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SummaryOut"];
                };
            };
        };
    };
    get_application_applications__application_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                application_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApplicationOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_application_applications__application_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                application_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_details_applications__application_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                application_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DetailsIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApplicationOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    change_status_applications__application_id__status_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                application_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StatusIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApplicationOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_note_applications__application_id__notes_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                application_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NoteIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApplicationOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    set_follow_up_applications__application_id__follow_up_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                application_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FollowUpIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApplicationOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    mark_sent_applications__application_id__sent_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                application_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SentIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApplicationOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    download_cv_cvs__cv_id___fmt__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                cv_id: number;
                fmt: "pdf" | "docx";
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/pdf": unknown;
                    "application/vnd.openxmlformats-officedocument.wordprocessingml.document": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    market_market_get: {
        parameters: {
            query?: {
                platform?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MarketOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_vacancy_vacancies_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VacancyIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApplicationOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_analysis_applications__application_id__analysis_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                application_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalysisOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    refresh_analysis_applications__application_id__analysis_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                application_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalysisOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    prepare_applications__application_id__prepare_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                application_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalysisOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_to_inbox_inbox_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InboxIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InboxOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    suggest_titles_discovery_titles_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TitlesOut"];
                };
            };
        };
    };
    search_links_discovery_links_get: {
        parameters: {
            query: {
                title: string;
                city?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchLinkOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    generate_cv_applications__application_id__cvs_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                application_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GenerateCVIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_cv_cvs__cv_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                cv_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CVDetailOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    edit_cv_cvs__cv_id__document_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                cv_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CVEditIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CVResultOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    screening_applications__application_id__screening_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                application_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ScreeningIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScreeningAnswerOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cover_applications__application_id__cover_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                application_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CoverOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    gap_applications__application_id__gaps_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                application_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GapIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GapOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_job_jobs__job_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_usage_usage_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UsageOut"];
                };
            };
        };
    };
    dev_token_dev_token_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DevLoginIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DevTokenOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
